# For the main source repo with random stuff in it
# tried dockerfilelint but too strict and disabling does not work
# cannot run check-json because notebooks do not conform
# cannot run check-executables-have-shebangs because of classes
# cannot run check-builtin-literals due to foreign python code
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-builtin-literals
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      # https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/detect_aws_credentials.py
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      # Generating a ruby error with run with all-files
      # https://github.com/jumanjihouse/pre-commit-hooks/issues/86
      #- id: markdownlint
        # https://github.com/jumanjihouse/pre-commit-hooks/issues/82
        # additional dependency bug in pre-commit v2.10
      - id: shellcheck
        additional_dependencies: []
      - id: shfmt
  - repo: local
    hooks:
      # https://github.com/markdownlint/markdownlint/blob/master/.pre-commit-hooks.yaml
      - id: markdownlintlocal
        name: Markdownlint Local
        description: Run Markdownlint locally
        entry: mdl
        language: ruby
        files: \.(md|mdown|markdown)$
