# https://squidfunk.github.io/mkdocs-material/creating-your-site/
# https://www.mkdocs.org/getting-started/
# Note that SchemaStore with LazyVim does not appear to work
# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
#
# this is used by monorepo as in the url so make it short
site_name: bin
site_url: https://richtong.github.io/bin/
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/
repo_url: https://github.com/richtong/bin
edit_uri: edit/main/docs

nav:
  - Home: index.md
  - install.md
  - setup.md
  - files.md
  - dev.md
  - test.md
  - special.md

theme:
  name: material
  # make sure you have logo's loaded here
  logo: media/logo_big.png
  favicon: media/logo_small.png
  # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  palette:
    primary: deep purple
    scheme: slate
    accent: indigo
  features:
    - content.action.edit
    - header.autohide
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
    # no more round trips to the server
    - navigation.instant
    # the address bar changes to nearest tag
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.instant.prefetch
    # tabs eliminates the side nav bar only use for big sites
    # - navigation.tabs
    # - navigation.tags.sticky
    - navigation.path
    - navigation.expand
    # prune reverse the expand
    # - navigation.prune
    - toc.follow
    - toc.integrate

# https://squidfunk.github.io/mkdocs-material/setup/extensions/
plugins:
  - mkdocstrings
  - redirects
  # allows the use of !include for mono repos
  - monorepo
  - search
  - awesome-pages
  - minify:
      minify_css: true
      minify_js: true
      minify_html: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
