# https://squidfunk.github.io/mkdocs-material/creating-your-site/
# https://www.mkdocs.org/getting-started/
# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Rich's Binary Utilities
site_url: https://bin.docs.tongfamily.com
theme:
  name: material
  palette:
    primary: blue
nav:
  - Home: index.md
  - Install: install.md
  - Setup: setup.md
  - Files: files.md
  - Dev: dev.md
  - Test: test.md
  - Special: special.md
