# https://squidfunk.github.io/mkdocs-material/creating-your-site/
# https://www.mkdocs.org/getting-started/
# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: RT's Binary Utilities
site_url: https://bin.docs.tongfamily.com
features:
  - header.autohide
theme:
  name: material
  palette:
    primary: blue
    scheme: slate
    accent: indigo
nav:
  - index.md
  - install.md
  - setup.md
  - files.md
  - dev.md
  - test.md
  - special.md
